### ISSUE TITLE
Missing unity4dv & DataSource4DS

### ISSUE THREAD

**Issue by mechpil0t** [keijiro/4DViewsTest#1]
On opening the project I get the following errors

Assets\Fdvfx\Runtime\VolumeRenderer.cs(39,9): error CS0246: The type or namespace name 'DataSource4DS' could not be found (are you missing a using directive or an assembly reference?)

Assets\Fdvfx\Runtime\VolumeRenderer.cs(6,7): error CS0246: The type or namespace name 'unity4dv' could not be found (are you missing a using directive or an assembly reference?)

2019.3.0f6

**Comment by keijiro** [comment]
You have to import 4DViews SDK manually. I can't include it to the repository due to the license restriction.

**Comment by keijiro** [comment]
Also you have to download and import the sample video data. The reason is the same.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by keijiro** [comment]
I wrote a brief README file. Please give a look to it.
