### ISSUE TITLE
Flipped Footage?

### ISSUE THREAD

**Issue by davidvjc** [keijiro/4DViewsTest#2]
Excellent sample - thanks for sharing. 

One quick question about the implementation:

I compared my footage from the "Volume Renderer" to the 4DViews plugin player. It appears to be flipped on the x-axis? 4DViews seems to add an empty parent GameObject with x set to -1. I tried doing that with the Volume Renderer, but it didn't work. 

Any idea how to fix this?

Unity 2019.3.13f1 (HDRP)
4DViews Plugin 3.2.0

**Comment by keijiro** [comment]
I didn't know the axis system difference between 4DViews and Unity.

I think it can be fixed by adding `*-1` to the x components in the following lines:

https://github.com/keijiro/4DViewsTest/blob/master/Assets/Fdvfx/Runtime/PointCloudBaker.shader#L49-L50

**Comment by davidvjc** [comment]
That worked in part - any particles are now in the correct position, but "Draw Surface" is still inverted.

**Comment by keijiro** [comment]
You can use the same workaround as used in the 4DViews sample (add an empty parent GameObject with x set to -1).

**Comment by davidvjc** [comment]
I tried that, but it seems to invert the mesh? Kinda looks like the normals are wrong now.

[https://drive.google.com/file/d/1CDYwpxJ6fEyaXm3U3ZcRwjQLHGBcwTBB/view?usp=sharing](url)

**Comment by davidvjc** [comment]
Simple fix is to change the "Surface" Material to Double-Sided. Thanks for your help!
